let theme = {
  foreground: "#ccc",
  background: "#000",
  // cursor: "",
  // black: "",
  red: "#FF0033",
  // green: "",
  // yellow: "",
  // blue: "",
  // magenta: "",
  // cyan: "",
  // white: "",
  // brightBlack: "",
  // brightRed: "",
  // brightGreen: "",
  // brightYellow: "",
  // brightBlue: "",
  // brightMagenta: "",
  // brightCyan: "",
  // brightWhite: "",
};